name: Build mission package

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Run extract script
        run: python extract.py --pack -d out
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Mission file
          path: out/*.miz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            out/*.miz
